apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: finyl-backend
  name: finyl-backend
  namespace: finyl
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: finyl-backend
  template:
    metadata:
      labels:
        app: finyl-backend
    spec:
      serviceAccountName: finyl-backend-sa
      containers:
        - image: asia-northeast3-docker.pkg.dev/notional-gist-410602/finyl-backend/finyl-backend:latest
          imagePullPolicy: Always
          name: finyl-backend
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: account-secret
                  key: mongodb_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: account-secret
                  key: mongodb_password
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: account-secret
                  key: mongodb_url
            - name: secret
              valueFrom:
                secretKeyRef:
                  name: account-secret
                  key: secret
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 2Gi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64
